{% set name = "nebula3-python" %}
{% set version = "3.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nebula3_python-{{ version }}.tar.gz
  sha256: da4693171079e9d5efb01a579f7fb62ef7655f6169cc2ff2cbb7b7d902e2cf3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6.2
    - pdm-backend
    - setuptools
    - pip
  run:
    - python >=3.6.2
    - future >=0.18.0
    - httplib2 >=0.20.0
    - pytz >=2021.1
    - six >=1.16.0
    - httpx >=0.22.0

test:
  imports:
    - nebula3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vesoft-inc/nebula-python
  summary: Python client for NebulaGraph v3
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
